repo: 'saas-website'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-10
  - html
  - css
  - css-order-modules-grid-type-main
  - modulifier
  - gridifier-unrestricted
  - typografier-unrestricted
  - modulifier-list-group
  - modulifier-buttons
  - modulifier-embed
  - google-fonts
  - html-good-semantics
  - forms
  - nav-hover
  - nav-focus
  - accessibility
  - aria-landmarks
  - main-link-focus

allFiles:
  html:
    has:
      - 'h2'
      - 'div'
      - 'img'

html:
  - path: 'index.html'
  - path: 'tour.html'
    has:
      - 'table'
      - 'table > caption'
      - 'thead'
      - 'tbody'
      - 'th[scope]'
      - 'tr'
      - 'td'
  - path: 'pricing.html'
  - path: 'sign-up.html'
    has:
      - ['form[method="POST"][action*="formspree.io"]', 'The `<form>` should submit to @@https://formspree.io/@@']
      - 'label[for]'
      - 'input[id][name]'
      - 'button[type="submit"]'

css:
  - path: 'css/main.css'
